name = "bodegacat"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "bodegacat-prod"

[env.staging]
name = "bodegacat-staging"

# Cloudflare Access configuration for admin routes
[[env.production.routes]]
pattern = "/admin/*"
zone_name = "your-domain.com"
custom_domain = true

# Environment variables
[vars]
NODE_ENV = "production"

# KV bindings for sessions
[[kv_namespaces]]
binding = "SESSION"
id = "placeholder-id"
preview_id = "placeholder-preview-id"

# Secrets (set these via wrangler secret put)
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET
