name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy to environment"
        required: true
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - app: main
            build_path: ./packages/main/build/client
            workspace: "@stripe-shop/main"
          - app: admin
            build_path: ./packages/admin/dist
            workspace: "@stripe-shop/admin"
    runs-on: ubuntu-latest
    name: Deploy ${{ matrix.app }}
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: enable corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/jod"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build shared dependencies
        run: yarn workspace @stripe-shop/shared-types build

      - name: Build
        run: yarn workspace ${{ matrix.workspace }} build
        env:
          NODE_ENV: production

      - name: Deploy to Cloudflare Pages (Push)
        if: github.event_name == 'push'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ matrix.build_path }} --project-name=${{ vars.CF_PROJECT_NAME }}${{ matrix.app == 'admin' && '-admin' || '' }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Cloudflare Pages (Manual)
        if: github.event_name == 'workflow_dispatch'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >-
            pages deploy ${{ matrix.build_path }}
            --project-name=${{ vars.CF_PROJECT_NAME }}${{ matrix.app == 'admin' && '-admin' || '' }}
            ${{ inputs.environment == 'staging' && '--branch=preview' || '' }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
